"""initial schema

Revision ID: 0eb02b8463b8
Revises: 
Create Date: 2026-07-20 17:20:07.619200

"""
from alembic import op
import sqlalchemy as sa


revision = '0eb02b8463b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('check_name', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('entity', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_quality_issues_check_name'), ['check_name'], unique=False)

    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('upstream', sa.String(length=100), nullable=False),
    sa.Column('package_version', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('data_sync_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sync_runs_job_name'), ['job_name'], unique=False)

    op.create_table('league_cap_parameters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('league_year', sa.String(length=10), nullable=False),
    sa.Column('salary_cap', sa.Integer(), nullable=False),
    sa.Column('luxury_tax', sa.Integer(), nullable=False),
    sa.Column('first_apron', sa.Integer(), nullable=False),
    sa.Column('second_apron', sa.Integer(), nullable=False),
    sa.Column('minimum_team_salary', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('extras', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('league_cap_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_league_cap_parameters_league_year'), ['league_year'], unique=True)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('training_period', sa.String(length=50), nullable=True),
    sa.Column('feature_list', sa.JSON(), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('validation_metrics', sa.JSON(), nullable=False),
    sa.Column('artifact_path', sa.String(length=300), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code_commit', sa.String(length=50), nullable=True),
    sa.Column('data_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_model_name'), ['model_name'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nba_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_inches', sa.Integer(), nullable=True),
    sa.Column('weight_lbs', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('draft_round', sa.Integer(), nullable=True),
    sa.Column('draft_number', sa.Integer(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_nba_player_id'), ['nba_player_id'], unique=True)

    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nba_team_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('year_founded', sa.Integer(), nullable=True),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('division', sa.String(length=20), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_abbreviation'), ['abbreviation'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_nba_team_id'), ['nba_team_id'], unique=True)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('contract_type', sa.String(length=30), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('no_trade_clause', sa.Boolean(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_player_id'), ['player_id'], unique=False)

    op.create_table('draft_picks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('original_team_id', sa.String(length=36), nullable=False),
    sa.Column('owning_team_id', sa.String(length=36), nullable=False),
    sa.Column('draft_year', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('protections', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['original_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['owning_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nba_game_id', sa.String(length=20), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('home_team_id', sa.String(length=36), nullable=True),
    sa.Column('away_team_id', sa.String(length=36), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_game_date'), ['game_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_nba_game_id'), ['nba_game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_season'), ['season'], unique=False)

    op.create_table('injuries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_player_id'), ['player_id'], unique=False)

    op.create_table('player_archetypes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('cluster_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('distances', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_archetype')
    )
    with op.batch_alter_table('player_archetypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_archetypes_player_id'), ['player_id'], unique=False)

    op.create_table('player_impact_estimates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('model_version_id', sa.String(length=36), nullable=False),
    sa.Column('tei', sa.Float(), nullable=False),
    sa.Column('tei_offense', sa.Float(), nullable=True),
    sa.Column('tei_defense', sa.Float(), nullable=True),
    sa.Column('tei_low', sa.Float(), nullable=True),
    sa.Column('tei_high', sa.Float(), nullable=True),
    sa.Column('availability', sa.Float(), nullable=True),
    sa.Column('minutes_estimate', sa.Float(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'model_version_id', name='uq_pie')
    )
    with op.batch_alter_table('player_impact_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_impact_estimates_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_impact_estimates_season'), ['season'], unique=False)

    op.create_table('player_season_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', 'stat_type', name='uq_pss')
    )
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_stats_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_pss_season', ['season', 'stat_type'], unique=False)

    op.create_table('player_team_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('player_team_history', schema=None) as batch_op:
        batch_op.create_index('ix_pth_player_season', ['player_id', 'season'], unique=False)

    op.create_table('rosters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('jersey_number', sa.String(length=10), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', 'season', 'valid_from', name='uq_roster_entry')
    )
    with op.batch_alter_table('rosters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rosters_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_rosters_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rosters_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_rosters_team_id'), ['team_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('focal_team_id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('max_added_payroll', sa.Integer(), nullable=True),
    sa.Column('willing_to_cross_tax', sa.Boolean(), nullable=False),
    sa.Column('willing_to_cross_first_apron', sa.Boolean(), nullable=False),
    sa.Column('willing_to_cross_second_apron', sa.Boolean(), nullable=False),
    sa.Column('untouchable_player_ids', sa.JSON(), nullable=False),
    sa.Column('preferred_outgoing_player_ids', sa.JSON(), nullable=False),
    sa.Column('positional_needs', sa.JSON(), nullable=False),
    sa.Column('min_retained_first_round_picks', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['focal_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_pct', sa.Float(), nullable=False),
    sa.Column('conference', sa.String(length=10), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('playoff_rank', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='uq_standing')
    )
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_standings_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_standings_team_id'), ['team_id'], unique=False)

    op.create_table('team_needs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('need_key', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('percentile', sa.Float(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'need_key', name='uq_team_need')
    )
    with op.batch_alter_table('team_needs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_needs_team_id'), ['team_id'], unique=False)

    op.create_table('team_season_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('stat_type', sa.String(length=20), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'stat_type', name='uq_tss')
    )
    with op.batch_alter_table('team_season_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_season_stats_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_season_stats_team_id'), ['team_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_sets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('trade_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_years',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('contract_id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.Column('guaranteed', sa.Integer(), nullable=True),
    sa.Column('player_option', sa.Boolean(), nullable=True),
    sa.Column('team_option', sa.Boolean(), nullable=True),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', 'season', name='uq_contract_year')
    )
    with op.batch_alter_table('contract_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_years_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_years_season'), ['season'], unique=False)

    op.create_table('player_game_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uq_pgs')
    )
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_stats_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_player_game_stats_player_id'), ['player_id'], unique=False)

    op.create_table('scenario_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'component', name='uq_scenario_weight')
    )
    with op.batch_alter_table('scenario_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenario_weights_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('trade_proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_proposals_scenario_id'), ['scenario_id'], unique=False)

    op.create_table('generated_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('llm_enhanced', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_reports_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('from_team_id', sa.String(length=36), nullable=False),
    sa.Column('to_team_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('protections', sa.String(length=200), nullable=True),
    sa.Column('is_hypothetical', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_assets_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('legality_status', sa.String(length=30), nullable=False),
    sa.Column('composite_utility', sa.Float(), nullable=True),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('uncertainty', sa.JSON(), nullable=False),
    sa.Column('sensitivity', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('data_version', sa.String(length=30), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_evaluations_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_rule_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('rule_code', sa.String(length=60), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('calculation', sa.JSON(), nullable=False),
    sa.Column('source_reference', sa.String(length=300), nullable=True),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_rule_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_rule_results_trade_id'), ['trade_id'], unique=False)

    op.create_table('trade_teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trade_proposals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id', 'team_id', name='uq_trade_team')
    )
    with op.batch_alter_table('trade_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trade_teams_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_teams_trade_id'))

    op.drop_table('trade_teams')
    with op.batch_alter_table('trade_rule_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_rule_results_trade_id'))

    op.drop_table('trade_rule_results')
    with op.batch_alter_table('trade_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_evaluations_trade_id'))

    op.drop_table('trade_evaluations')
    with op.batch_alter_table('trade_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_assets_trade_id'))

    op.drop_table('trade_assets')
    with op.batch_alter_table('generated_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_reports_trade_id'))

    op.drop_table('generated_reports')
    with op.batch_alter_table('trade_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_proposals_scenario_id'))

    op.drop_table('trade_proposals')
    with op.batch_alter_table('scenario_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenario_weights_scenario_id'))

    op.drop_table('scenario_weights')
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_stats_player_id'))
        batch_op.drop_index(batch_op.f('ix_player_game_stats_game_id'))

    op.drop_table('player_game_stats')
    with op.batch_alter_table('contract_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_years_season'))
        batch_op.drop_index(batch_op.f('ix_contract_years_contract_id'))

    op.drop_table('contract_years')
    op.drop_table('comparison_sets')
    op.drop_table('transactions')
    with op.batch_alter_table('team_season_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_season_stats_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_season_stats_season'))

    op.drop_table('team_season_stats')
    with op.batch_alter_table('team_needs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_needs_team_id'))

    op.drop_table('team_needs')
    with op.batch_alter_table('standings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_standings_team_id'))
        batch_op.drop_index(batch_op.f('ix_standings_season'))

    op.drop_table('standings')
    op.drop_table('scenarios')
    with op.batch_alter_table('rosters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rosters_team_id'))
        batch_op.drop_index(batch_op.f('ix_rosters_season'))
        batch_op.drop_index(batch_op.f('ix_rosters_player_id'))
        batch_op.drop_index(batch_op.f('ix_rosters_is_current'))

    op.drop_table('rosters')
    with op.batch_alter_table('player_team_history', schema=None) as batch_op:
        batch_op.drop_index('ix_pth_player_season')

    op.drop_table('player_team_history')
    with op.batch_alter_table('player_season_stats', schema=None) as batch_op:
        batch_op.drop_index('ix_pss_season')
        batch_op.drop_index(batch_op.f('ix_player_season_stats_player_id'))

    op.drop_table('player_season_stats')
    with op.batch_alter_table('player_impact_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_impact_estimates_season'))
        batch_op.drop_index(batch_op.f('ix_player_impact_estimates_player_id'))

    op.drop_table('player_impact_estimates')
    with op.batch_alter_table('player_archetypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_archetypes_player_id'))

    op.drop_table('player_archetypes')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_player_id'))

    op.drop_table('injuries')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_season'))
        batch_op.drop_index(batch_op.f('ix_games_nba_game_id'))
        batch_op.drop_index(batch_op.f('ix_games_game_date'))

    op.drop_table('games')
    op.drop_table('draft_picks')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_player_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_nba_team_id'))
        batch_op.drop_index(batch_op.f('ix_teams_abbreviation'))

    op.drop_table('teams')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_nba_player_id'))
        batch_op.drop_index(batch_op.f('ix_players_full_name'))

    op.drop_table('players')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_name'))

    op.drop_table('model_versions')
    with op.batch_alter_table('league_cap_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_league_cap_parameters_league_year'))

    op.drop_table('league_cap_parameters')
    with op.batch_alter_table('data_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sync_runs_job_name'))

    op.drop_table('data_sync_runs')
    op.drop_table('data_sources')
    with op.batch_alter_table('data_quality_issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_quality_issues_check_name'))

    op.drop_table('data_quality_issues')
    # ### end Alembic commands ###
