"""store completed trades, so a recommendation can be answered with evidence

Revision ID: 7a7a8e16cd96
Revises: e5c81f4a7b30
Create Date: 2026-08-24 13:37:59.690597

R6-1 ingests ten seasons of Basketball-Reference transaction pages so a proposed trade can
be shown the completed trades that most resemble it. Nothing in the existing schema can
hold one.

`transactions` is one row per (player, team, type) and cannot express a trade at all: the
2025-26 corpus alone contains 11 trades with three or more teams, and one with seven, where
the same franchise both sends and receives. Direction has to live on the asset.

`trade_proposals` is the wrong table for the opposite reason. A proposal is something a
user built and can edit; this is something that happened and cannot be edited. Sharing a
table would turn "did this occur?" into a column.

Three columns exist to record what the source did **not** say, and they are the reason this
is a schema change rather than a JSON blob:

- `unparsed_assets` keeps asset phrases the grammar could not read. Five of 2,364 asset
  legs across ten seasons — an unlinked name, a pick with no round. A trade with an
  unreadable leg is still a real trade, and recording the leg as absent would let the
  retrieval engine compare against a deal that never happened.
- `note_binding_ambiguous` marks a pick whose condition could not be bound to it uniquely,
  because the trade moved two picks of the same year and round. 85 of 859 pick legs. The
  note is attached to both rather than assigned to one by guessing.
- `resolution_method` records how a printed name became a player here, and is `ambiguous`
  or `none` where it did not. Nothing is fuzzy-matched.

Reversible: both tables drop cleanly and hold only derived rows, which
`make import-transactions` rebuilds from the local snapshot.
"""
import sqlalchemy as sa
from alembic import op


revision = '7a7a8e16cd96'
down_revision = 'e5c81f4a7b30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('season', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('n_teams', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('unparsed_assets', sa.JSON(), nullable=False),
    sa.Column('trade_exception_team_ids', sa.JSON(), nullable=False),
    sa.Column('trade_exception_unresolved', sa.JSON(), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_provider', 'source_record_id', name='uq_historical_trade')
    )
    with op.batch_alter_table('historical_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_trades_season'), ['season'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_trades_transaction_date'), ['transaction_date'], unique=False)

    op.create_table('historical_trade_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trade_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('from_team_id', sa.String(length=36), nullable=True),
    sa.Column('to_team_id', sa.String(length=36), nullable=True),
    sa.Column('from_abbreviation', sa.String(length=10), nullable=False),
    sa.Column('to_abbreviation', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=True),
    sa.Column('source_player_slug', sa.String(length=20), nullable=True),
    sa.Column('resolution_method', sa.String(length=30), nullable=True),
    sa.Column('via_draft_rights', sa.Boolean(), nullable=False),
    sa.Column('draft_year', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('conveyance', sa.String(length=20), nullable=True),
    sa.Column('note_text', sa.Text(), nullable=True),
    sa.Column('note_binding_ambiguous', sa.Boolean(), nullable=False),
    sa.Column('later_selected', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['historical_trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_trade_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_trade_assets_trade_id'), ['trade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historical_trade_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_trade_assets_trade_id'))

    op.drop_table('historical_trade_assets')
    with op.batch_alter_table('historical_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historical_trades_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_historical_trades_season'))

    op.drop_table('historical_trades')
    # ### end Alembic commands ###
