"""add media_assets manifest

Revision ID: ac4624025dbb
Revises: 0eb02b8463b8
Create Date: 2026-07-21 23:13:55.652034

"""
from alembic import op
import sqlalchemy as sa


revision = 'ac4624025dbb'
down_revision = '0eb02b8463b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('nba_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('match_method', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=100), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=False),
    sa.Column('source_provider', sa.String(length=50), nullable=False),
    sa.Column('source_record_id', sa.String(length=100), nullable=True),
    sa.Column('source_retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'file_path', name='uq_media_asset_path')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index('ix_media_entity', ['entity_type', 'nba_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_media_entity')

    op.drop_table('media_assets')
    # ### end Alembic commands ###
